### PR TITLE
Update to Go18

### LINKED ISSUE #423: Fix dependencies
Running make run returns this error:

`explorer.go:35:2: no required module provides package github.com/NYTimes/gziphandler: go.mod file not found in current directory or any parent directory; see 'go help modules'`

It appears to be new Go versions and dependency management.

### PR DESCRIPTION
**Pull request by Senyoret1**
Fixes #423

Changes:
- go.mod was added and the server should now work well with Go18.
- The readme was updated.
- The Travis file was updated to use the new Go version.

Does this change need to mentioned in CHANGELOG.md?
Yes

### CODE REVIEW

**Comment by Senyoret1** [comment]
The last commit includes the following changes:
-	Now the Go server returns the correct mime type for JavaScript files, to make the app work well with modern brownser without an intermediate server.
-	Now there are CLI params to configure the web server address:port, the URL of the Skycoin node and the path of the folder with the precompiled UI files. Run “go run explorer.go -h” to see the param list.
-	The branch was updated.

**Comment by Senyoret1** [comment]
The last commit replaces gometalinter with golangci-lint. It works similar to how it works on the Skycoin wallet. Also, some changes were made to make the tests pass.

**Comment by Senyoret1** [comment]
The last commit inslcudes info in the readme and a new helper command 1n the makefile, for installing the linters in a local enviroment.

**Review by 0pcom — APPROVED** [review]
looks really good, nicely done

**Pull request merged**
