### PR TITLE
added navigable pagination to blocks page 

### LINKED ISSUE #45: Pagination is not navigable
Pagination does not use urls so reloading or going back resets the pagination

### PR DESCRIPTION
**Pull request by efosao**
Resolves #45

This is my first contrib to this repo, so please let me know if any changes and/or adjustments are required. Tnxs!

### CODE REVIEW

**Comment by gz-c** [comment]
Sorry we just merge a full rewrite, but we still need this feature for it

Also send your sky address, we can send bounty for it when done

**Comment by efosao** [comment]
@gz-c thanks man. I'll update the PR as soon as issue #61 is resolved (broken build). I can't build the javascript project at the moment. `make build-ng` is failing.

**Comment by efosao** [comment]
@gz-c PR is ready. Thanks!

Skycoin wallet: 2Eu8RKK4u5i7GiG3UguC53FSyE7tcPrwyUP

**Comment by gz-c** [comment]
@montycrypto need you to review

**Comment by montycrypto** [comment]
Hi @efosao, nice solution to the navigation issue. Thanks! I found two bugs which I fixed: https://github.com/skycoin/skycoin-explorer/pull/67

I created a dev branch, to which you can aim next PR's. This time I created a PR for your code myself. Next time also please don't include new build files (/dist) or binaries (explorer).

Looking forward to seeing more code from you!

**Comment by efosao** [comment]
@montycrypto thanks for merging the code. How is the bounty handled for the fix?

**Pull request closed without merging**
