### PR TITLE
Changes to the search mechanism

### PR DESCRIPTION
**Pull request by Senyoret1**
In issue https://github.com/skycoin/skycoin-explorer/issues/59 the ability to search by block hash was requested. However, the change was not easy to implement because there is no way to distinguish the transaction hashes from the block hashes and the browser simply redirected the user to the screen of the type of data searched (not knowing if the hash was from a block or a transaction there was no way to redirect the user correctly). Due to all this, changes were made to the search system.

Now, when performing a search, the user is redirected to an intermediate screen that simply says "searching". In case the user searches for an address or a block number, the screen simply performs the search and, if successful, redirects the user to the corresponding screen (the searched data is stored in a service to avoid unnecessarily repeat the search after the redirection). If the search is not successful, "No results found" is shown. Redirections from the intermediate search screen do not affect the correct functioning of the "back" button of the browser.

If the user searches for a 64-character hash, the search screen first tries to find the transaction that matches that hash and then, if it does not find it, it tries to find the block that matches that hash (as was suggested in https://github.com/skycoin/skycoin-explorer/issues/59 ). If a transaction or block is found, the user is redirected accordingly, if not, "No results found" is shown.

### CODE REVIEW

**Comment by Senyoret1** [comment]
Due to the problems indicated in https://github.com/skycoin/skycoin-explorer/issues/83 , and trying to create a simple solution, I made some changes that could satisfactorily solve the problem of searching for addresses.

Now, when performing a search, the code first checks if the string has 64 characters. If so, and if it is a valid hexadecimal string, the code search for a transaction or block. If it is not a valid hexadecimal string, the execution is stopped and a message is displayed indicating that no results were found.

If the string does not have 64 characters, it is assumed that the user wants to find a block (by its number) or an address. If the text entered by the user is a positive integer, the code searches for a block. If not, the application searches for an address, but only if the text contains only valid characters for a Base58 encoding. If the text is not a positive integer or contains characters that are not valid in the Base58 encoding, the execution ends and a message indicating that no results were found is displayed.

This method is acceptably effective in identifying what type of data should be searched on the server, while not overcompleting the code by doing server-side validations. Probably the biggest disadvantage is that there is not a exhaustive validation of the addresses, but that does not seem to be a very important problem.

In case you want a more exhaustive validation of the addresses, it is possible to do it on the client side adding as dependencies create-hash (https://www.npmjs.com/package/create-hash) and bs58 (https://www.npmjs.com/package/bs58) and creating some functions. These two libraries seem to work well and are used in well-proven projects such as CryptoCoinJS (and a large number of wallets that use the library). Probably the only disadvantage would be that it would increase the size of the Javascript file.

Any comment on this is welcome.

**Comment by Senyoret1** [comment]
After merging https://github.com/skycoin/skycoin-explorer/pull/72 a conflict arose with this pull request. In the last conmit added the https://github.com/skycoin/skycoin-explorer/pull/72 code, to avoid problems.

**Comment by samuelvisscher** [comment]
Took a different approach, but could reuse some of your code. Please do take a look at it and let me know what you think!

https://github.com/skycoin/skycoin-explorer/pull/91/commits/6bb71848f000b33bfb2020b2993b87c0297f67e0

**Comment by Senyoret1** [comment]
@samuelvisscher I took a look, as you asked.

The approach you used is much simpler than mine and has the advantage that it is easier to read and avoids complicating the code. I think the only things I would see as disadvantages are that when searching for a block by hash the client searches twice for the same data (once in search-bar.component.ts to see if the block exists and again after navigating to /app/block) and that there are fewer validations to the data entered by the user. Regarding the latter, I'm not sure if Skycoin addresses have between 27 and 34 characters, I know it is true for Bitcoin addresses, but I am not totally sure in this case, I think that's why @gz-c proposed in https://github.com/skycoin/skycoin-explorer/issues/83#issuecomment-356662268 to do a complete validation of the addresses. Maybe one way to make it a bit more reliable would be to change the order of the if-else on line 20 of search-bar.component.ts to something like this (I made the changes in the comment, not directly in a code editor, so there may be some small errors):

```
if (hashVal.length === 64) {
    this.explorer.getBlockByHash(hashVal).subscribe(
        block => this.router.navigate(['/app/block', block.id]),
        () => this.router.navigate(['/app/transaction', hashVal])
    )
} else if (hashVal.length < 20) {
    this.router.navigate(['/app/block', hashVal]);
} else {
    this.router.navigate(['/app/address', hashVal]);
}
```

However, if it is certain that Skycoin addresses have between 27 and 34 characters, it is not necessary to change anything.

**Comment by samuelvisscher** [comment]
Good idea!

**Pull request closed without merging**
