### PR TITLE
New design

### PR DESCRIPTION
**Pull request by kzviagina**
this PR should be merged after main site new design released

### CODE REVIEW

**Comment by AlexSugak** [comment]
@gz-c  @samuelvisscher  we will be adding more fixes today. Please do not merge this PR until the [main site's](https://www.skycoin.net/) new design is released. (you can see the current work in progress on [staging2](https://staging2.skycoin.net/)

**Comment by gz-c** [comment]
@AlexSugak @kzviagina ok let us know when to merge and redeploy. explorer does not automatically deploy like skycoin.net does

**Comment by AlexSugak** [comment]
This is how it looks now 
image

**Comment by samuelvisscher** [comment]
Let me know when you want me to review!

**Pull request merged**
