### PR TITLE
Design improvements

### PR DESCRIPTION
**Pull request by Senyoret1**
This PR does not change the appearance of the explorer in an important way, but it improves the readability of the data and fixes small errors.

Currently the explorer has problems showing the block page on small screens:

block1

This PR fixes the consistency of the lines in the "stats" area and modifies the format of the dates in the table, so that them fits correctly: The PR also vertically centers the content of the tables, to improve the appearance on small screens:

block2

Also, currently the amounts are difficult to read, since it is difficult to differentiate the commas from the points. The same thing happens to the dates, they are difficult to read because they contain many numbers:

block3

This PR changes the style of the dates and the amouts, to make them easier to read:

block4

The necessary changes to the e2e tests were also made.

### CODE REVIEW

**Comment by Senyoret1** [comment]
@gz-c It seems that there are problems with the ci/dockercloud test, it never starts.

**Comment by olemis** [comment]
@Senyoret1 we'll take a look into this to fix asap .

**Comment by Senyoret1** [comment]
@olemis Thanks :thumbsup:, I asked gz-c because I thought it could be a configuration change made by him.

**Comment by olemis** [comment]
@Senyoret1 I guess the configuration change is about blocking the merge based on Docker CI check results

**Comment by Senyoret1** [comment]
@olemis In fact, the configuration change that I was thinking about was simply adding the 
ci/dockercloud check, because I had not seen it before, hehe. I did not really know if it is possible to merge the PR without that check, but now I see that the UI says "Required". In any case, something must be done to make it possible to merge this and future PRs, but at this moment I think there is no hurry, unless it is planned to launch a new release soon.

**Comment by olemis** [comment]
@Senyoret1 @gz-c did this because few days ago we had an issue caused but Docker Cloud builds failing , and also because changeset breaking the build has to be fixed prior to merge .

**Pull request merged**
