### PR TITLE
[travis] Fixed #174 Added the notification of the travis

### LINKED ISSUE #174: Add travis telegram notifications
See https://github.com/skycoin/skycoin/pull/1259/files for how

### PR DESCRIPTION
**Pull request by stdevHan**
Fixes #174 

Changes:
-Change in the configuration file of travis `.travis.yml`, enabling the notification to travis

### CODE REVIEW

**Comment by Senyoret1** [comment]
The Telegram notifications were already added in the develop branch, so this will cause a conflict when updating the master branch with the changes made in develop.

**Comment by olemis** [comment]
@Senyoret1 shall we closed this PR then ?

**Comment by Senyoret1** [comment]
I think so. unless it is also necessary to add the Email notification included in this PR. But in that case it may be necessary to do it in another PR, because this PR would merge the changes made on develop into master and I don't really know if that should be done right now.

**Comment by olemis** [comment]
@Senyoret1 let's close it 👍

**Pull request closed without merging**
