### PR TITLE
Update Angular to v12

### PR DESCRIPTION
**Pull request by Senyoret1**
Changes:
- Angular was updated to v12.

Does this change need to mentioned in CHANGELOG.md?
No

### CODE REVIEW

**Comment by iketheadore** [comment]
@Senyoret1 can you merge the changes from `develop`, thanks.

**Comment by iketheadore** [comment]
I got errors when run `npm install` in the root of the project, I'm using node v14.15.5.

```
> fsevents@1.2.13 install skycoin/skycoin-explorer/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'nan'
Require stack:
- skycoin/skycoin-explorer/node_modules/webpack-dev-server/node_modules/fsevents/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:133:18)
    at Object.runInThisContext (vm.js:310:38)
    at internal/process/execution.js:77:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'skycoin/skycoin-explorer/node_modules/webpack-dev-server/node_modules/fsevents/[eval]'
  ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit ($HOME/.nvm/versions/node/v14.15.5/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "$HOME.nvm/versions/node/v14.15.5/bin/node" "$HOME.nvm/versions/node/v14.15.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd $HOME/go/src/github.com/skycoin/skycoin-explorer/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v14.15.5
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

**Comment by Senyoret1** [comment]
I fixed a bug that prevented compilation, but not related. I tried to reproduce the issue and was unable to do it. I’m using Node v14.15.1, so I don’t think that should be the problem.

Could you please try again using `npm ci` isntead of `npm install`?

**Comment by Senyoret1** [comment]
It appears that one of the component of the e2e tests that is updated automatically (probably the Chrome driver or Chrome itself) was changed a few hours ago and that made the e2e tests to start failing. That appears to be why the test were ok in https://github.com/skycoin/skycoin-explorer/pull/370 but not in https://github.com/skycoin/skycoin-explorer/commit/68d71196e167a6730dd87fcc23798079b130ff93 . I changed a bit the code of some tests to make them work well again.

**Pull request merged**
